### ISSUE TITLE
Request: Ogg Vorbis and Opus

### ISSUE THREAD

**Issue by Feichtmeier** [ClementBeal/audio_metadata_reader#1]
Hi @ClementBeal and thanks for creating this libary! 

I am currently try to find a pure dart replacement for metadata god  which has a rust dependency which makes it hard to test and is also not very fast, for [MusicPod](https://github.com/ubuntu-flutter-community/musicpod)

Your library works great for MP3s

However some of my users use flac and ogg vorbis and opus.

It would be great if you could add those too :) Thanks in advance and best regards

**Comment by ClementBeal** [comment]
Hi @Feichtmeier ,

Your comment sparked a little of joy in me! 

About your request, I'll check in the week how to fix the issue. It's a strange behavior because I'm using this library to build my custom audio player too and it works 90% of the time correctly with Ogg and FLAC.

I'll keep you updated

**Comment by ClementBeal** [comment]
Added!  There might be some issues for the duration calculation. 

Sometimes it would need to parse all the file to get the correct duration. I'll think about a solution!
